### ISSUE TITLE
ideit proofing the timesheet

### ISSUE THREAD

**Issue by Phil12026** [The-Three-Stooges-and-Renee/William-Tell#3]
if you hit punch in or punch out twice in a row (same button) it'll do two time outs or two time ins instead of compensating for id10t (or fat finger) error.

**Comment by thegeekkid** [comment]
That was kind of on purpose.  Prof Stolley is always saying that we shouldn't limit the user, and let them decide how to interact with the site.  I don't always agree with that, but in this case I thought it would work.  If you think it should be changed, it shouldn't be that hard of a change.  :)

**Comment by Phil12026** [comment]
Two clock ins in a row doesn't make sense.  As a user of the current system, I'd rather the system assume my fat fingered the button than be dumb enough to do two clock ins next to each other. The alternetive is is we do for example two clock in, than an empty clock out automatically spawns between the two clock ins for the user to fill in?  The last might be the best of both worlds? Not sure how hard to program though.

**Comment by thegeekkid** [comment]
Here's a use case:
I'm punching out now, but forgot to punch in earlier.  Now I want to punch out then mark my time for time in.  Could be a thing.  Yes, you could just type in the time-in first and then punch out; but some users may not realize that.

**Comment by Phil12026** [comment]
So my second idea where if they punch out where the last one was also punch out we auto spawn a punch in between the two punch outs?

**Comment by thegeekkid** [comment]
Define "auto spawn"?

**Comment by Phil12026** [comment]
We start with them having punched in for the morning:
"Some time in."

They hit punch out to go to lunch and we get:
"some time in
some time outA"

They come back from lunch but forget to punch in again and hit punch out at the end of the day.  They have have:
"some time in
some time outA
a blank time in slot for them to fill
some time outB"

Does that help?

**Comment by thegeekkid** [comment]
Yes.  As best as I can tell, that was what I had originally had in mind.  There is a bug in the JS that stopped it from doing that though, so I'll fix that and it should work right.
